### ISSUE TITLE
Mobile Safari log in 

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#24]
- Tap nominate opens a new tab. 
- Says "Error. Not logged in. You are not logged in. Please login and try again"

**Comment by robertocarroll** [comment]
http://stackoverflow.com/questions/38208842/facebook-js-sdk-login-popups-not-working-in-facebook-app-and-if-popuup-blockers

> Use the redirect flows as specified in the FB Advanced section.

https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

Its the only way to reliably login or set permissions with FB and Twitter on todays mobile landscape with a myriad of in native-app 'webviews' to display webpages and sites.

**Comment by robertocarroll** [comment]
This is the url it opens:

`https://mobile.facebook.com/v2.8/dialog/oauth?app_id=148573185670966&client_id=148573185670966&display=touch&domain=wearethoughtfox.github.io&e2e=%7B%7D&locale=en_US&origin=2&redirect_uri=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2F96nq-xsaNcg.js%3Fversion%3D42%23cb%3Df1e600855%26domain%3Dwearethoughtfox.github.io%26origin%3Dhttp%253A%252F%252Fwearethoughtfox.github.io%252Ff183b74858%26relation%3Dopener%26frame%3Dfd17a7d7&response_type=token%2Csigned_request&return_scopes=true&scope=public_profile%2Cemail%2Cuser_friends%2Cpublish_actions&sdk=joey&version=v2.8`

**Comment by robertocarroll** [comment]
- http://www.devils-heaven.com/facebook-javascript-sdk-login/
- http://stackoverflow.com/questions/41524925/facebook-javascript-sdk-with-mobile

**Comment by pauldwaite** [comment]
Hm, odd — works for me, at least on https://wearethoughtfox.github.io/amnesty-facebook/app/.

I’m on iOS 10.3.1. Tried it when logged into Facebook, and when not logged in.

**Comment by robertocarroll** [comment]
Closing.
