### ISSUE TITLE
After posting a message on Facebook, we show the Amnesty website in an iframe. Is that right?

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#36]
If so, cool, but it does look a bit odd if the user hasn’t already visited the Amnesty site (unlikely, I guess), as then they get Amnesty’s cookie warning taking up half of the iframe.

![iframe-um](https://cloud.githubusercontent.com/assets/138270/25871118/4dfafe9c-34fe-11e7-920d-cb001992c262.jpg)

**Comment by robertocarroll** [comment]
This is meant to show some kind of call to action (which we don't have yet) in an iFrame, so this bit was just demonstrating showing the content in an iFrame. The content on the iFrame will actually vary according to the user's region (one of five, I think) which we need to work out from their location provided by Facebook. Hurray!

**Comment by pauldwaite** [comment]
Gotcha. Will we have a default call-to-action to show, in case any real users don’t have a location (like our test users don’t)?

**Comment by robertocarroll** [comment]
Yes, good idea.

**Comment by robertocarroll** [comment]
Closing. See #53
