### ISSUE TITLE
PERF: possibly include background image inline

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#40]
This might not cost too much bandwidth, and would avoid an extra HTTP request.

**Comment by robertocarroll** [comment]
I'm not clear exactly what this means. At the moment it's: 

`<div class="vh-100 dt w-100 tc bg-dark-gray white cover" id="main" style="background:url(images/464656512.jpg) no-repeat center;">`

What would inline be? Also the image changes with the language, so I'm not sure if that makes any difference?

**Comment by robertocarroll** [comment]
> including it as a data-url, rather than a file.

But not possible in current set-up.
