### ISSUE TITLE
PERF: possibly include everything inline

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#41]
As we’re a single page app, if we’re not expecting the code to change regularly, we could include all assets (CSS, JavaScripts, images) inline on the index page.

This reduces the number of HTTP requests (which is beneficial assuming we’re serving over HTTP 1; possibly not if we’re serving over HTTP 2), and may result in better compression.

See also #40.

**Comment by robertocarroll** [comment]
Closing this one unless you have something to add?

**Comment by pauldwaite** [comment]
Nope, all good.
