### ISSUE TITLE
IE 10: after loading the friends list or posting a message, the background goes weird.

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#42]
#### Steps to reproduce

1. In IE 10, visit the app.
2. Look at the page’s background image.
3. Click on the “Nominate with Facebook” button.
4. Look at the page’s background image again.
5. Select a friend, and post a message .
6. Look at the page’s background image once more.

#### Expected behaviour

In steps 4 and 6, the background image looks the same as it does in step 2.

#### Actual behaviour

The background image looks a bit weird.

#### Notes

I didn’t notice this in Edge or IE 11 on Windows 8, and having seen it in IE 10 on Windows 7, I tried and failed to reproduce it in IE 11 on Windows 7.

I think the problem appears when content is added to the page that makes it tall enough to require scrolling, and goes away when enough content is removed so that it doesn’t require scrolling any more.

I presume it’s some kind of IE 10-specific bug related to `background-size:cover`.

![ie10-odd-0](https://cloud.githubusercontent.com/assets/138270/25923468/9bf7713e-35d5-11e7-8b09-2698f42147cb.jpg)

![ie10-odd-2](https://cloud.githubusercontent.com/assets/138270/25923166/259986a4-35d4-11e7-8128-c1620e1b57db.jpg)

**Comment by robertocarroll** [comment]
Closing for now: http://www.pcworld.com/article/3019538/windows/microsoft-officially-dumps-internet-explorer-8-9-and-10.html

Could revisit if the app takes off.
