### ISSUE TITLE
IE 9: list of friends does not appear

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#43]
#### Steps to reproduce

1. In IE 9, visit the app
2. Click on the “Nominate with Facebook” button
3. If necessary, log into Facebook.

#### Expected behaviour

A list of your Facebook friends appears in the app.

#### Actual behaviour

No list appears.

#### Notes

We don’t get any errors logged in the console, and the HTTP request to the graph API appears to be successful. I guess we’re using some JavaScript that IE 9 doesn’t support, and that we’re handling the error so that the failure is silent.

![ie9-1](https://cloud.githubusercontent.com/assets/138270/25923917/d94d2cac-35d7-11e7-9bed-9ff2744642c5.jpg)
![ie9-2](https://cloud.githubusercontent.com/assets/138270/25923916/d949616c-35d7-11e7-9519-044d8d1e5504.jpg)

**Comment by robertocarroll** [comment]
Closing for now: http://www.pcworld.com/article/3019538/windows/microsoft-officially-dumps-internet-explorer-8-9-and-10.html

Could revisit if the app takes off.
