### ISSUE TITLE
There’s no visual indication when buttons are pressed

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#44]
#### Steps to reproduce

1. Visit the app.
2. Click on the “Nominate with Facebook” link/button

#### Expected behaviour

The button/link’s styles change somehow when the mouse button is in the pressed state.

#### Actual behaviour

The styles do not change.

#### Notes

See also #45.

**Comment by robertocarroll** [comment]
Any ideas about making the spinner in the button look better? 

https://github.com/wearethoughtfox/amnesty-facebook/commit/d60cf6cd4556564895d0b356d7df8a4b244124fb

e.g. keeping the same size button etc.

**Comment by pauldwaite** [comment]
> Any ideas about... keeping the same size button

I do! https://github.com/wearethoughtfox/amnesty-facebook/commit/fa0c46dfada869f65fce8615506f97aea201e472

**Comment by robertocarroll** [comment]
This all seems to be fixed now. Thanks in no small part to your efforts!
