### ISSUE TITLE
There’s no visual indication that we’re waiting for the Facebook API

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#45]
#### Steps to reproduce

1. Visit the app
2. Click on the “Nominate with Facebook” button
3. Log into Facebook if necessary
4. Select a friend
5. Click on the submit button.

#### Expected behaviour

While we wait for the Facebook API to post the message, there is some visual indication that something is happening.

#### Actual behaviour

There’s no visual indication that anything is happening.

#### Notes

See also #44.

**Comment by robertocarroll** [comment]
I came across this pattern and thought it was quite neat for these kinds of situations: 

https://mattrothenberg.github.io/prototyping-playbook/simulating-async-events

What do you reckon?

**Comment by pauldwaite** [comment]
Sure, that looks good.

(I presume he’s removing the spinner after two seconds just to demonstrate the effect.)

**Comment by pauldwaite** [comment]
I can have a crack at implementing that today if we’re good with it.

**Comment by robertocarroll** [comment]
Any idea how to centre that spinner?

https://github.com/wearethoughtfox/amnesty-facebook/commit/434a57e0e5b2ba91a433d4efbdc72c1f08319d69

It's immune to the usual tactics.

**Comment by robertocarroll** [comment]
I did text-align center on the parent and then display inline-block on the child.

**Comment by pauldwaite** [comment]
> Any idea how to centre that spinner?

I do! Although I was just looking at the spinner in the “Nominate with Facebook” button. I can’t figure out when the one inside `#loadedFacebook` shows up.

https://github.com/wearethoughtfox/amnesty-facebook/commit/fa0c46dfada869f65fce8615506f97aea201e472
