### ISSUE TITLE
The app silently fails if the user logs out of Facebook in another tab after granting it access

### ISSUE THREAD

**Issue by pauldwaite** [wearethoughtfox/amnesty-facebook#47]
#### Steps to reproduce

1. Visit the app
2. Click on the “Nominate with Facebook” button
3. Log into Facebook if necessary
4. Select a friend
5. Open another browser tab, visit Facebook in it, and log out.
6. Back in the app’s tab, submit your message.

#### Expected behaviour

The app tells you that you’re no longer logged into Facebook, and ideally remembers the message so that you can post it once you’re logged in again.

#### Actual behaviour

The app silently fails to post the message.

**Comment by robertocarroll** [comment]
With each call to the API, check the response to see if it says that the user isn’t logged in any more.

**Comment by robertocarroll** [comment]
If not, 

> kick off the Facebook login process again, and then re-try our API call to post the message once they’re logged in.

**Comment by robertocarroll** [comment]
I remember discussing this but I'm not clear about how to implement. Please could we go over it again when you get chance.

**Comment by robertocarroll** [comment]
You've fixed this one I believe.

**Comment by pauldwaite** [comment]
Yup, I think so.
