### ISSUE TITLE
Select friends view - design pattern

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#7]
I'm not sure about the design pattern for choosing a friend to nominate. From the wireframes:

![wireframes-full_png](https://cloud.githubusercontent.com/assets/1565953/24744792/3f465030-1ac4-11e7-8a21-9c7a215f0526.png)

I think something like this would work better: 

![tachyons_-_lists___follower_notifications](https://cloud.githubusercontent.com/assets/1565953/24744988/0074190e-1ac5-11e7-9c6b-c35d11002193.png)

But the user can only select one. Not sure how to handle that?

**Comment by robertocarroll** [comment]
So each one could be a selectable box and when selected it has a highlight around it, but the user could only select one:

![pasted_image_06_04_2017__13_18](https://cloud.githubusercontent.com/assets/1565953/24747119/738ae6b4-1acc-11e7-94a3-9cc561c9543b.png)

**Comment by paulwaitehomeoffice** [comment]
Sure, that could be good. I’d suggest square profile pictures, as that seems to be the Facebook idiom:

![square](https://cloud.githubusercontent.com/assets/25032977/24770986/d94e24fc-1b03-11e7-997b-d886c8f1c06f.jpg)

**Comment by robertocarroll** [comment]
And the blue highlight. Good point. Thanks!

**Comment by robertocarroll** [comment]
I think they were happy with this design pattern rather than the one in the wireframes.
