### ISSUE TITLE
Put templates in scripts tags in index.html and copy using a UNIX command

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-facebook#8]
In an effort to keep away from grunt, web pack, browserify, etc. I wondered about putting the templates in script tags in index.html 

sed -n "/<-- Templates-- >/,/<-- Templates-- >/p" app/index.html > docs/index.html

And then trigger that script in package.json

Would something that work?

**Comment by paulwaitehomeoffice** [comment]
I’m not very good with sed — what does that script do?

**Comment by robertocarroll** [comment]
I had you down as a UNIX expert! Going to put this on hold for the prototype and just copy and paste.

**Comment by pauldwaite** [comment]
Oh lord, no I actually write my npm scripts in JavaScript rather than bash or whatever, because at least there’s only one set of documentation (i.e. Node’s) to look at.
